name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands using SSH key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_SERVER_HOST }}
        username: ${{ secrets.SSH_SERVER_USERNAME }}
        password: ${{ secrets.SSH_SERVER_PASSWORD }}
        port: ${{ secrets.SSH_SERVER_PORT }}
        script: |
          cd csi_website_scripts/
          ./csi-website-deployment-script.sh

    - name: Switch to staging branch
      run: git checkout staging

    - name: Merge changes from master
      run: git merge master --no-edit

    - name: Push changes to staging branch
      run: |
        git push origin staging
