# name: Deploy to Server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy to Server
#         run: |
#           # Add the server's host key to known_hosts
#           ssh-keyscan 128.199.23.207 >> $HOME/.ssh/known_hosts
      
#           # Get the server's host key fingerprint
#           SERVER_FINGERPRINT=$(ssh-keyscan -t rsa 128.199.23.207 | ssh-keygen -lf - | awk '{print $2}')
      
#           # Compare the server's host key fingerprint with the one stored in the secret
#           if [ "$SERVER_FINGERPRINT" != "${{ secrets.SSH_HOST_KEY_FINGERPRINT }}" ]; then
#             echo "Host key fingerprint does not match. Aborting deployment."
#             exit 1
#           fi
      
#           # SSH into the server and run the deployment script
#           ssh csi-client@128.199.23.207 "cd csi_website_scripts && ./temp.sh"
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
name: deploy to server
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_SERVER_HOST }}
        username: ${{ secrets.SSH_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: whoami