name: Deploy to CSI Server

on:
  push:
    branches:
      - master # or specify your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Remote Server
      run: |
        ssh csi-client@128.199.23.207 'bash -s' ./temp.sh
      env:
        SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
