name: deploy to server
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_SERVER_HOST }}
        username: ${{ secrets.SSH_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd csi_website_scripts/
          ./csi-website-deployment-script.sh