name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H $SSH_SERVER_HOST >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh -i ~/.ssh/id_rsa $SSH_SERVER_USER@$SSH_SERVER_HOST "bash -s" < $REMOTE_PATH
        env:
          SSH_SERVER_HOST: ${{ secrets.SSH_SERVER_HOST }}
          SSH_SERVER_USER: ${{ secrets.SSH_SERVER_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
