name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 128.199.23.207 >> ~/.ssh/known_hosts
        env:
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
      
      - name: List files in working directory
        run: ls -l

      - name: Deploy code to server
        run: |
          ssh -o StrictHostKeyChecking=no csi-client@128.199.23.207 'bash -s' < /home/csi-client/csi_website_scripts/temp.sh
        env:
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
